apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  labels:
    app.kubernetes.io/name: obsidian-livesync
data:
  local.ini: |
    [couchdb]
    single_node = true
    max_document_size = 50000000
    n = 1

    [chttpd]
    require_valid_user = true
    require_valid_user_except_for_up = true
    max_http_request_size = 4294967296
    enable_cors = true

    [chttpd_auth]
    require_valid_user = true
    require_valid_user_except_for_up = true

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    enable_cors = true

    [cors]
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    origins = app://obsidian.md,capacitor://localhost,http://localhost
