apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  labels:
    app.kubernetes.io/name: obsidian-livesync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
