apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app.kubernetes.io/name: obsidian-livesync
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: obsidian-livesync
  ports:
    - name: http
      port: 5984
      targetPort: http
      nodePort: 30984
      protocol: TCP
