apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

helmCharts:
- name: strimzi-kafka-operator
  repo: oci://quay.io/strimzi-helm
  releaseName: strimzi-cluster-operator
  includeCRDs: true


