apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

helmCharts:
- name: strimzi-kafka-operator
  repo: oci://quay.io/strimzi-helm
  releaseName: strimzi-cluster-operator
  includeCRDs: true

# resources:
#   - kafka.yaml
  # - https://strimzi.io/examples/latest/kafka/kraft/kafka-single-node.yaml

# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/storage/volumes/0/size
#         value: 10Gi
#     target:
#       kind: KafkaNodePool
#       name: dual-role
