apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - https://raw.githubusercontent.com/ray-project/kuberay/v1.0.0/ray-operator/config/samples/ray-service.text-summarizer.yaml

patches:
  - target:
      kind: RayService
      name: text-summarizer
    patch: |-
      - op: remove
        path: /spec/rayClusterConfig/workerGroupSpecs/0/template/spec/tolerations
  - target:
      kind: RayService
      name: text-summarizer
    patch: |-
      - op: remove
        path: /spec/rayClusterConfig/workerGroupSpecs/0/template/spec/containers/0/resources
  - target:
      kind: RayService
      name: text-summarizer
    patch: |-
      - op: remove
        path: /spec/rayClusterConfig/headGroupSpec/template/spec/containers/0/resources
