apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  hostnames:
    - httpbin.quanianitis.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /httpbin/
    backendRefs:
    - name: httpbin
      port: 80

