apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  namespace: default
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
spec:
  ingressClassName: cilium
  rules:
  - host: httpbin.quanianitis.com
    http:
      paths:
      - path: /httpbin/
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
