apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: infra/kustomize/cert-manager
    repoURL: https://github.com/ian-chan-ml/homelab.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true

