apiVersion: v1
kind: Secret
metadata:
  name: oci-envoyproxy
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: envoyproxy-oci
  type: helm
  url: docker.io/envoyproxy
  enableOCI: "true"
