apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdgkl-backend-kafka
  labels:
    app.kubernetes.io/name: gdgkl-backend-kafka
    quanianitis.com/service-type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gdgkl-backend-kafka
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gdgkl-backend-kafka
        quanianitis.com/service-type: gdgkl-backend-kafka
    spec:
      containers:
        - name: gdgkl-backend-kafka
          image: ghcr.io/ian-cq/gdgkl-backend-kafka:v0.3.0
          # ports:
          #   - containerPort: 8080
          #     name: http
          #     protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              # cpu: "500m"
