apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.31.0
    releaseName: kube-state-metrics
    includeCRDs: true
