apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth

resources:
  - reference-grant.yaml

helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.7.0
    releaseName: oauth2-proxy-argocd
    namespace: oauth
    valuesFile: values-argocd.yaml
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.7.0
    releaseName: oauth2-proxy-grafana
    namespace: oauth
    valuesFile: values-grafana.yaml
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.7.0
    releaseName: oauth2-proxy-prometheus
    namespace: oauth
    valuesFile: values-prometheus.yaml
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.7.0
    releaseName: oauth2-proxy-kubernetes
    namespace: oauth
    valuesFile: values-kubernetes.yaml
