persistence:
  enabled: false
testFramework:
  enabled: false
service:
  type: NodePort
  nodePort: 31000
adminUser: admin
adminPassword: admin
grafana.ini:
  auth:
    disable_login_form: true
  auth.anonymous:
    enabled: true
    org_role: Admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
