fullnameOverride: argocd
crds:
  install: true
  keep: true
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: false
server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
configs:
  params:
    server.insecure: true
  cm:
    users.anonymous.enabled: "true"
  rbac:
    policy.default: role:admin
  secret:
    argocdServerAdminPassword: $2a$10$NkGtPsPpIUU.j7fz./qq2OMb2QLrCu1KCHf.hMRHJuyMJJBZTP7La
    argocdServerAdminPasswordMtime: "2026-06-25T15:30:00Z"
