apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
spec:
  provider:
    onepassword: 
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080/
      vaults:
        quanianitis.com: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1password
            namespace: external-secrets
            key: token
