apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 1password-token-duplicate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: 1password-server-token
      property: token
