apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    version: v0.15.1
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    includeCRDs: true
    valuesFile: values.yaml

namespace: external-secrets
