apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-server-tls
  namespace: monitoring
spec:
  secretName: prometheus-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: prometheus.62a.quanianitis.com
  dnsNames:
    - prometheus.62a.quanianitis.com
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
