apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/docs/examples/hello-world/rabbitmq.yaml
  
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: rabbitmq
    target:
      kind: RabbitmqCluster
      namespace: default
