apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: firefly
    server: https://kubernetes.default.svc
  source:
    path: infra/charts/firefly
    repoURL: https://github.com/ian-cq/homelab.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
