apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  source:
    path: infra/charts/httpbin
    repoURL: https://github.com/ian-chan-ml/homelab.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
