apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: public-oidc
  namespace: gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
  oidc:
    provider:
      issuer: https://accounts.google.com
    clientIDRef:
      name: google-oauth-client
    clientSecret:
      name: google-oauth-client
    cookieDomain: 62a.quanianitis.com
    cookieNames:
      idToken: IdToken
      accessToken: AccessToken
    logoutPath: /logout
    scopes:
      - openid
      - email
      - profile
  jwt:
    providers:
      - name: google
        issuer: https://accounts.google.com
        remoteJWKS:
          uri: https://www.googleapis.com/oauth2/v3/certs
        extractFrom:
          cookies:
            - IdToken
        claimToHeaders:
          - claim: email
            header: x-auth-email
  authorization:
    defaultAction: Deny
    rules:
      - name: allowlist
        action: Allow
        principal:
          jwt:
            provider: google
            claims:
              - name: email
                valueType: String
                values:
                  - quanianitis@gmail.com
                  - work@quanianitis.com
                  - main@quanianitis.com
