apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: plane
---
