defaultSettings:
  defaultDataPath: /data/longhorn
  defaultReplicaCount: 1
  upgradeChecker: false
  backupTarget: nfs://192.168.1.50:/backup/longhorn

persistence:
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain

ingress:
  enabled: false

service:
  ui:
    type: NodePort
    nodePort: 30980

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false
